
print("\033[1mBRIZA, Pryllanie Kirsten\033[0m")
print("BSCpE 1-4 | CMPE 102")
print("\n")

print("\033[1m1. RHYME\033[0m")
print("Twinkle, twinkle, little star,")
print("   How I wonder what you are!")
print("     Up above the world so high,")
print("     Like a diamond in the sky.")
print("Twinkle, twinkle, little star,")
print("   How I wonder what you are.")
print("\n")

print("\033[1m2.1 PUP HYMN\033[0m")
print("Sintang Paaralan")
print("Tanglaw ka ng bayan")
print("Pandayan ng isip ng kabataan")
print("Kami ay dumating nang salat sa yaman")
print("Hanap na dunong ay iyong alay")
print("Ang layunin mong makatao")
print("Dinarangal ang Pilipino")
print("Ang iyong aral, diwa, adhikang taglay")
print("PUP, aming gabay")
print("Paaralang dakila")
print("PUP, pinagpala")
print("Gagamitin ang karunungan")
print("Mula sa iyo, para sa bayan")
print("Ang iyong aral, diwa, adhikang taglay")
print("PUP, aming gabay")
print("Paaralang dakila")
print("PUP, pinagpala")
print("\n")

print("\033[1m2.2 PUP VISION\033[0m")
print("A Leading Comprehensive Polytechnic University in Asia")
print("\n")

print("\033[1m2.3 PUP MISSION\033[0m")
print("Advance an inclusive, equitable,")
print("and globally relevant polytechnic")
print("education towards national development.")
print("\n")

print("\033[1m3. GOLDEN LYRICS by Huntrix\033[0m")
print("I was a ghost, I was alone, hah")
print("Eoduwojin apgilsoge (Ah)")
print("Given the throne, I didn't know how to believe")
print("I was the queen that I'm meant to be")
print("I lived two lives, tried to play both sides")
print("But I couldn't find my own place")
print("Called a problem child 'cause I got too wild")
print("But now that's how I'm getting paid, kkeuteopsi on stage")
print("I'm done hiding, now I'm shining like I'm born to be")
print("We're dreaming hard, we came so far, now I believe")
print("We're goin' up, up, up, it's our moment")
print("You know together we're glowin'")
print("Gonna be, gonna be golden")
print("Oh, up, up, up with our voices")
print("Yeongwonhi kkaejil su eomneun")
print("Gonna be, gonna be golden")
print("Oh, I'm done hidin' now I'm shinin' like I'm born to be")
print("Oh, our time, no fears, no lies")
print("That's who we're born to be")
print("Waited so long to break these walls down")
print("To wake up and feel like me")
print("Put these patterns all in the past now")
print("And finally live like the girl they all see")
print("No more hiding, I'll be shining like I'm born to be")
print("'Cause we are hunters, voices strong, and I know I believe")
print("We're goin' up, up, up, it's our moment")
print("You know together we're glowing")
print("Gonna be, gonna be golden")
print("Oh, up, up, up, with our voices")
print("Yeongwonhi kkaejil su eomneun")
print("Gonna be, gonna be golden")
print("Oh, I'm done hidin', now I'm shining like I'm born to be")
print("Oh, our time, no fears, no lies")
print("That's who we're born to be")
print("You know we're gonna be, gonna be golden")
print("We're gonna be, gonna be")
print("Born to be, born to be glowin'")
print("Balge binnaneun uri")
print("You know that it's our time, no fears, no lies")
print("That's who we're born to be")
print("\n")

print("\033[1m5. LUPANG HINIRANG\033[0m")
print("Bayang magiliw")
print("Perlas ng Silanganan")
print("Alab ng puso")
print("Sa dibdib mo'y buhay")
print("Lupang Hinirang")
print("Duyan ka ng magiting")
print("Sa manlulupig")
print("'Di ka pasisiil")
print("Sa dagat at bundok")
print("Sa simoy at sa langit mong bughaw")
print("May dilag ang tula")
print("At awit sa paglayang minamahal")
print("Ang kislap ng watawat mo'y")
print("Tagumpay na nagniningning")
print("Ang bituin at araw niya")
print("Kailan pa ma'y 'di magdidilim")
print("Lupa ng araw ng luwalhati't pagsinta")
print("Buhay ay langit sa piling mo")
print("Aming ligaya na 'pag may mang-aapi")
print("Ang mamatay ng dahil sa iyo")
print("\n")

print("\033[1m5. COMPUTER SET\033[0m")
print("╭───────────────────•───────────────────╮")
print("│                                       │")
print("│  ** ** *     **      **    ** ** *    │              ╭──────────╮      ")
print("│  **     **   **      **    **     **  │              │          │      ")
print("│  ** ** *     **      **    ** ** *    │              │──────────│      ")
print("│  **          **      **    **         │              │──────────│      ")
print("│  **            * ** *      **         │              │          │      ")
print("│                                       │┈┈┈┈┈┈┈┈┈┈┈┈┈┈│    ๑     │      ")
print("╰───────────────────────────────────────╯              │          │      ")
print("                )    (         ╰┈┈┈┈┈┈┈┈┈┈┈┈┈╮         │          │      ")
print("                ──────                       ┊         ╰──────────╯      ")
print("  ╭────────────────────────────────────╮    ___      ")
print("  │ ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣ │   ( ๑ )     ")
print("  │ ⃣⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣ │   ╰~~~╯     ")
print("  │ ⃣⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣  ⃣ │             ")
print("  ╰────────────────────────────────────╯             ")